obj-$(CONFIG_MI_PERFMGR) += perfmgr.o
perfmgr-$(CONFIG_MI_PERFMGR) += perfmgr_ioctl.o
perfmgr-$(CONFIG_MI_PERFMGR) += perfmgr_remap.o
perfmgr-$(CONFIG_MI_PERFMGR) += perfmgr_main.o
perfmgr-$(CONFIG_MI_PERFMGR) += perfmgr_policy.o
perfmgr-$(CONFIG_MI_PERFMGR_GPU) += perfmgr_gpu.o
