# MIUI ADD: Performance_TurboSched
# END Performance_TurboSched
# obj-y                                  += perfmgr/
# MIUI ADD: DCVS ARBI
obj-y                                   += dcvs_arbi/
# END DCVS ARBI