# MIUI ADD: Performance_TurboSched
# END Performance_TurboSched
obj-y                                  += perfmgr/
# MIUI ADD: DCVS ARBI
obj-y                                   += dcvs_arbi/
# END DCVS ARBI
# MIUI ADD: Power_UnionPowerCore
obj-y                                   += unionpower/
# END Power_UnionPowerCore

# MIUI ADD: Power_PowerSaveModeV2
obj-y                                   += powersave/
# END Power_PowerSaveModeV2
