# MIUI ADD: Power_UnionPowerCore
obj-y                                   += unionpower/
# END Power_UnionPowerCore

# MIUI ADD: Power_PowerSaveModeV2
obj-y                                   += powersave/
# END Power_PowerSaveModeV2

# MIUI ADD: Performance_TurboSched
obj-$(CONFIG_MI_SPEED_TOUCH)            += input/
# END Performance_TurboSched
